"""Veinte vidas concretas para el camino sin modelo.

La primera de cada (modo, final) es la que usa el banco corto.
"""
from __future__ import annotations

CATALOG: list[dict] = [
    {
        "id": "canal-marca",
        "mode": "creator",
        "ending": "victory",
        "title": "POV: Conviertes un canal chico en una marca",
        "premise": "Conviertes un canal chico de YouTube en una marca, grabando de noche en Madrid.",
        "name": "TechVibe",
        "city": "Madrid",
        "need": ("canal", "video", "patrocin", "visita", "suscriptor", "8.000", "sofá"),
        "ban": ("playoff", "gimnasio", "básquet", "basquet", "utilero", "dueño del equipo"),
        "close": "lo logras",
        "paras": [
            "Tienes 24 años y vives en un departamento de 32 metros en Madrid, con la cama contra la ventana. De día contestas mails. De noche el canal se llama TechVibe y subes videos de cosas que nadie te explicó: por qué el cargador se calienta, qué auricular de 20 dólares suena igual que uno de 200. Anoche el video lo vieron 11 personas. Tres eran tus primos. Tienes 214 suscriptores.",
            "Subes «Por qué tu cargador se calienta» a la una de la mañana. La luz del aro se cae a la mitad y lo dejas, porque si lo repites no lo publicas. El comentario que te importa llega a las tres: alguien de tu ciudad dice que por fin entendió por qué el teléfono quema. Te quedas mirando esa línea más de la cuenta.",
            "El canal sigue chico. Un martes el vecino golpea la pared porque grabas la misma frase por cuarta vez. Ese video torpe se queda en 40 visitas. Apagas, te sientas en el suelo y al día siguiente no despega. Vuelves a la oficina con la sensación de haber inventado un mundo que solo existe para ti.",
            "Pasan unos meses. Una tarde, en el metro, «Por qué tu cargador se calienta» salta a 1.200.000 visitas. No puedes gritar. Llegas a casa con el teléfono en la mano: 18.000 suscriptores, más o menos uno cada sesenta que lo vieron. El cuarto se ve distinto, aunque no moviste la silla.",
            "Una marca de cables te escribe. El mail está en spam. El patrocinio son 8.000 dólares por dos videos, si dices el producto cuando lo usas de verdad. Lo lees dos veces. Contestas que si no lo usas, no lo nombras. Esa noche grabas la respuesta como si le hablaras a una sola persona.",
            "Hay una semana floja. El video del domingo, una comparativa de baterías, se queda en 6.000 visitas y no crece. En el almuerzo escribes el siguiente título en una servilleta: «Lo que nadie te dice de la batería a los dos años». La guardas en el bolsillo y vuelves al mail de la oficina.",
            "No renuncias. Ocho mil dólares en Madrid no pagan el alquiler de un año. Compras el sofá verde que querías, de 1.400, no el de 300, un escritorio de roble y el micrófono. El alquiler sigue saliendo del mail de la oficina. Armas el setup el domingo y te sacas una foto en el espejo para el primer frame. Tus padres se sientan en ese sofá y miran entero «Por qué tu cargador se calienta». No aplauden. Se quedan.",
            "Al final lo logras. TechVibe es tuyo, la luz es la de tu cuarto, y esa vida te queda.",
        ],
    },
    {
        "id": "halcones-noche",
        "mode": "sports_team",
        "ending": "victory",
        "title": "POV: Compras un equipo deportivo en crisis",
        "premise": "Compras los Halcones de Puerto Norte, un equipo al borde del cierre, y lo llevas a una noche llena.",
        "name": "Halcones de Puerto Norte",
        "city": "Puerto Norte",
        "need": ("equipo", "gimnasio", "halcones", "contrato", "valor de mercado", "48.000"),
        "ban": ("subasta", "canal de youtube"),
        "close": "lo logras",
        "paras": [
            "Tienes 26 años. Trabajas en una oficina y los sábados juegas cuando la cancha todavía está abierta. En Puerto Norte, los Halcones están a punto de desaparecer. El gimnasio huele a humedad. Una noche cuentas 17 personas. El base se llama Mateo Ruiz, tiene 22 años y cobra 4.000 dólares al mes, 48.000 al año. Su valor de mercado está en 180.000: lo que pagaría otro club, no el sueldo. El gimnasio cabe a unas 900 personas y esa noche hay 17.",
            "Firmas. Pones 18.000 dólares, lo que tienes ahorrado. Unas personas de la ciudad ponen el resto. Te dan unas llaves que no abren todas las puertas. Le dices a Mateo que el contrato de 48.000 se paga el día 1, no cuando sobre. Él no sonríe. Asiente.",
            "El primer mes el lugar está vacío. Pierden de local y una de las 17 personas se va en el primer tiempo. Mateo te dice, en el pasillo, que si vuelves a prometer cosas que no puedes pagar, se va. No prometes. Compras hielo y cintas. El valor de mercado sigue en 120.000 y esa cifra te pesa más que el marcador.",
            "Pasan los meses. El equipo pierde seguido y tú aprendes los nombres de los que se quedan. La puerta del sábado, cuando entra gente de verdad, deja unos 600 dólares. Con eso y lo ahorrado dejas la oficina un lunes: la caja cabe en un asiento. Antes, no. Tus padres vienen un viernes. Tu madre pregunta si esto es de verdad. Le dices que sí, bajito.",
            "Hay una racha floja que cuesta dormir. El marcador duele y el gimnasio vuelve a sonar a hueco. Esa semana no inventas un discurso. Abres igual el sábado. Mateo anota 24 y no mira a la grada: mira el reloj, porque el contrato se cumple si el partido se juega.",
            "Después, una noche el gimnasio llega a lo que cabe: 900 personas, no más. Alguien que no conoces se queda en la puerta. El valor de mercado de Mateo pasa de 120.000 a 260.000 y un club de la capital pregunta por él. Tú le enseñas el papel. Él se queda un año más, por los 4.000 al mes y por la gente que ya no se va a la mitad.",
            "Te mudas a un departamento a cuatro cuadras cuando la puerta ya paga el mes, con un sofá que no es el más barato y una foto de la noche de las 900 personas en la heladera. Viajas en el autobús a un pueblo de al lado. Llueve contra el vidrio. Pierden por dos puntos. En el regreso Mateo se duerme con la cabeza en la ventana y tú piensas que el viaje también es el equipo.",
            "Al final lo logras. El lugar se llena y los Halcones siguen siendo tuyos.",
        ],
    },
    {
        "id": "halcones-subasta",
        "mode": "sports_team",
        "ending": "loss",
        "title": "POV: Compras un equipo y lo pierdes",
        "premise": "Compras los Halcones cansados y la etapa se cierra en una subasta.",
        "name": "Halcones de Puerto Norte",
        "city": "Puerto Norte",
        "need": ("subasta", "gimnasio", "contrato", "valor de mercado"),
        "ban": ("lo logras",),
        "close": "se cae",
        "paras": [
            "Tienes 29 años cuando compras los Halcones de Puerto Norte, un equipo que ya venía cansado. El día de la firma hace frío y el gimnasio tiene una gotera justo arriba del banquillo. La alero se llama Lucía Ferrer. Su contrato es de 36.000 dólares al año. Su valor de mercado figura en 90.000, y el papel ya se ve viejo.",
            "Los primeros partidos crees que con presencia alcanza. Te sientas cerca, aprendes los nombres, pagas el autobús de 400 dólares cuando no hay otra forma de llegar al pueblo de al lado. Lucía anota 18 y te busca con la mirada al terminar. Esa noche duermes.",
            "La gente no vuelve. Una noche juegan y oyes tu propia voz rebotar. Cuentan 12 personas. El marcador se inclina y los jugadores dejan de mirarte. No es rabia. Es cansancio. El valor de mercado de Lucía baja a 40.000. El contrato de 36.000 sigue ahí, puntual, aunque la grada no.",
            "Pasan dos años. Vendes el auto por 7.500 dólares. Alcanza para el mes de Lucía, 3.000, y el autobús. No para el resto del plantel. Tus padres te dicen que pares y tú les contestas que el sábado se acomoda. El sábado no se acomoda. Lucía deja las zapatillas en el locker y no vuelve el jueves.",
            "Hay un partido que ganan de local y por una noche el gimnasio suena con 900 personas. Crees que el año se da vuelta. A la semana siguiente vuelven a jugar y cuentan los mismos doce de siempre. La noche buena no alcanza para cambiar la calle. El valor de mercado queda en 22.000.",
            "Llegas tarde a una conversación que ya no es una conversación. Lees el papel en la cocina, de pie, con el abrigo puesto. El contrato de Lucía ya no está en tu mesa: está en la de otro club, por 20.000 dólares y un año.",
            "Llega una oferta que no es una oferta: es una subasta. Cierras el gimnasio una última tarde. Cuentas las sillas. Son 180. Dejas las llaves sobre el escritorio y la foto del partido de las 900 personas se queda en el cristal de la oficina.",
            "Al final se cae. Se cierra esa etapa. Te quedas con el ruido de una pelota en un lugar vacío, y con la certeza de que lo intentaste hasta que el contrato ya no daba.",
        ],
    },
    {
        "id": "siete-dias",
        "mode": "freeform",
        "ending": "victory",
        "title": "POV: Tienes 7 días para gastar un billón de dólares",
        "premise": "Tienes 7 días para gastar un billón de dólares y volver a tu calle.",
        "name": "siete días",
        "city": "",
        "need": ("día", "gast", "dólar"),
        "ban": ("playoff", "gimnasio", "básquet", "equipo pasa", "startup"),
        "close": "lo logras",
        "user_proposed": True,
        "paras": [
            "Tienes 27 años y te despiertas con un mensaje que no parece real: tienes siete días para gastar un billón de dólares. El reloj marca 9:14. Afuera tu vida sigue igual. El café de la esquina cuesta 2 dólares y el dueño ya te tiene el vaso listo.",
            "El primer día no puedes decidir ni el desayuno. Pagas la cuenta de todo el bar: 640 dólares. La gente se ríe porque cree que es un chiste. Tú miras el comprobante y el número no cabe en la pantalla.",
            "El segundo día compras silencio: una casa vacía al lado del mar, por 4.200.000 dólares, sin muebles. Te sientas en el suelo y escuchas el agua. El dinero no hace ruido. Eso te asusta más que la cifra.",
            "A mitad de semana el gasto se vuelve concreto. Cubres el hospital del barrio con 12.000.000 dólares, el alquiler de tu edificio por diez años y el taller de la esquina que iba a cerrar el viernes, con 80.000 para que el dueño no baje la persiana. No se lo dices a nadie.",
            "El cuarto día te sientas en un banco y miras pasar gente que no sabe nada. También compras un piano de 18.000 dólares que no sabes tocar. A las dos horas lo dejas en una escuela, de noche, con una nota sin firma. El gasto que te gusta es el que no te queda a ti.",
            "Hay una noche, la quinta, en la que te detienes. Son las tres de la mañana. Entiendes que gastar también es elegir qué no se compra: no compras una vida distinta para escapar de la tuya. El reloj sigue.",
            "El sexto día vuelves a tu calle. Dejas el café de siempre pagado por un año, 730 dólares, y no se lo dices a nadie. El dueño te mira raro cuando dejas el sobre.",
            "El séptimo día el plazo se acaba a las 9:14. Te sientas en tu cama de siempre. Al final lo logras: gastaste, volviste, y esa vida te queda.",
        ],
    },
    {
        "id": "cocina-domingo",
        "mode": "chef",
        "ending": "pyrrhic",
        "title": "POV: Abres un restaurante y llegas arriba",
        "premise": "Abres un restaurante chico y la sala se llena, y el domingo en familia no vuelve.",
        "name": "la esquina",
        "city": "Lima",
        "need": ("cocina", "restaur", "cubierto"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "no vuelve",
        "paras": [
            "Tienes 31 años y cocinas en un restaurante que no es tuyo, en un turno que termina cuando Lima ya duerme. Un local de 28 metros en la esquina se desocupa. El alquiler es de 1.800 dólares. Las llaves pesan más que la sartén. El plato que quieres servir cabe en una hoja: arroz de domingo, el de tu padre, a 14 dólares.",
            "Abres con doce cubiertos. La primera noche vienen tus amigos y un señor que se equivocó de puerta. Se queda por el olor del ajo y paga 14 dólares sin mirar la cuenta. Tú cuentas el cajón tres veces: 168 dólares. No alcanza. Igual apagas tarde y sonríes.",
            "Los meses siguientes la sala llega a 48 cubiertos un sábado. Una reseña dice tu nombre y el arroz de domingo. Dejas de ver la luz del día. El menú pasa de 14 a 32 dólares y hay lista de espera de 20 nombres. El domingo, que era el almuerzo en casa de tus padres, pasa a ser el servicio más largo.",
            "Llega una crítica que cambia la reserva de un mes. Brindas en la cocina con el equipo, de pie, con el delantal puesto. Nadie se sienta. El sábado son 64 cubiertos a 32 dólares: unos 2.000, el alquiler del mes en una noche. Tú sigues emplatando el arroz y ya no pruebas la sal: la pruebas el ayudante.",
            "Tu padre cumple 64 ese domingo y tú estás emplatando. Le mandas una foto del postre. Él contesta con un punto. Nada más. El servicio de esa noche son 64 cubiertos. Aplauden. Tú estás en la puerta de la cocina con las manos temblando, y no hay nadie de tu casa para verlo.",
            "Una noche el servicio se cae: se quema una salsa, se va la luz diez minutos, alguien se queja en voz alta del arroz a 32 dólares. Recuperas el ritmo. Al final aplauden igual. Tú no escuchas el aplauso. Escuchas el punto del mensaje.",
            "A la una de la mañana la sala queda vacía y huele a limón. Te mudas a un apartamento arriba del local para no perder el primer turno. Compras la mesa que querías, no la plegable, y no cenas en ella ni una vez. La silla de tu padre, en la otra casa, quedó vacía otra vez.",
            "Llegas arriba. La sala está llena, la crítica está en la puerta, y el almuerzo de los domingos no vuelve.",
        ],
    },
    {
        "id": "cancion-anuncio",
        "mode": "musician",
        "ending": "ironic",
        "title": "POV: Tu canción se vuelve famosa",
        "premise": "Tu canción de la cocina termina en un anuncio y la gente la canta sin saber tu nombre.",
        "name": "Cocina a oscuras",
        "city": "Buenos Aires",
        "need": ("canción", "anuncio", "reproduc"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "no es como lo imaginabas",
        "paras": [
            "Tienes 23 años y tu canción vive en el teléfono, en notas de voz que nadie pidió. Se llama «Cocina a oscuras». Una noche la tocas en un bar de Buenos Aires donde la gente habla más fuerte que tú. Cobras 40 dólares y un vaso. Igual terminas. En la plataforma la escuchan 200 personas, casi todas con tu apellido.",
            "Alguien del fondo te escribe al otro día. No es un sello. Es una marca de bebidas. Quieren esa melodía, la que escribiste en la cocina, para un anuncio de quince segundos. Ofrecen 22.000 dólares, una cifra cerrada: ni un peso más cada vez que el anuncio suene. El alquiler vence el jueves: son 450.",
            "Firmas. Grabas la versión corta en un estudio que huele a cables. Cuando la escuchas con la voz en off del producto, no la reconoces, y al mismo tiempo es tuya. El contrato dice 22.000 dólares y tu nombre en letra chica, al final, donde nadie lee.",
            "El anuncio está en todas partes. En el colectivo, en el mercado, en la radio del bar. «Cocina a oscuras» suena 40.000.000 de veces en el anuncio. Esas pasadas no te depositan nada: el contrato ya se cobró. La gente tararea. Nadie sabe tu nombre. Saben el estribillo y el nombre de la bebida.",
            "Te llaman para una gira de veranos en shoppings. El cachet es de 1.500 dólares por fecha. El sonido es bueno. El público canta. Tú miras sus bocas y escuchas el comercial, no la noche en la cocina. Hay una fecha en la que el salón está a medias y el eco te devuelve el estribillo tarde, un segundo después de tu voz.",
            "Escribes otra canción, de noche, sin marca. La tocas una vez en el mismo bar. Cobras otra vez 40 dólares. Tres personas callan. El resto sigue hablando. Esa es la canción que querías, y no la pone nadie en el colectivo. En la plataforma se queda en 800 reproducciones.",
            "Tu madre tiene la radio prendida mientras lava un vaso. Entra el anuncio. Ella tararea y te mira, orgullosa. Tú sonríes y sientes el golpe justo ahí: te reconoce el estribillo, no la cocina donde la escribiste. Con los 22.000 dólares te compras la guitarra que mirabas en la vidriera, de 1.900, no la de oferta.",
            "Consigues lo que querías, y no es como lo imaginabas. La canción es famosa. Tú sales por la puerta de servicio con la funda golpeándote la pierna.",
        ],
    },
    {
        "id": "estudio-letrero",
        "mode": "business",
        "ending": "plateau",
        "title": "POV: Dejas la oficina y te quedas con un estudio chico",
        "premise": "Dejas la oficina y tu estudio se queda chico, y es tuyo.",
        "name": "el estudio",
        "city": "Ciudad de México",
        "need": ("estudio", "oficina", "encargo"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "se queda",
        "paras": [
            "Tienes 28 años y diseñas de noche, en la mesa de la cocina, en Ciudad de México, para clientes que a veces pagan. Un encargo chico son 800 dólares y tarda tres semanas. Un día dejas la oficina, donde ganabas 1.900 al mes, y te quedas con tres encargos y el miedo concreto de fin de mes.",
            "El primer año no es una película de despegue. Es una fila de mails. Uno dice que sí y paga 2.400 dólares por una identidad. Otro se enfría y se lleva el anticipo de 400 en silencio. Aprendes a cobrar antes de prometer la luna. Hay un mes flojo en el que el estudio no despega y cenas arroz dos semanas.",
            "Armas un estudio chico con una socia. El letrero es de papel los primeros meses. Después es de verdad, de 600 dólares, y todavía se ve chico desde la vereda. El alquiler es de 1.100. Eso te gusta más de lo que admites.",
            "Hay un mes en el que un cliente grande quiere comprarte el estudio entero por 180.000 dólares. Cenas con esa oferta en el bolsillo. Al otro día dices que no. No por un discurso. Porque te gusta abrir la puerta tú, a la mañana, y ver tu nombre en el vidrio.",
            "Pasan cuatro años. No hay imperio. Hay una calle que ya te ubica, una mesa de roble que elegiste tú, no la más barata, y trabajo que alcanza: un mes bueno son 6.000 dólares entre cuatro encargos. Te mudas a un departamento a dos cuadras, con una foto del letrero de papel enmarcada en el pasillo.",
            "Un mes entero vive de un solo cliente, 2.200 dólares, y apagas la luz temprano para no mirar la bandeja. Al otro mes entran dos encargos chicos, de gente de la cuadra, y con eso pagas el alquiler. No es una cima. Es poder quedarte.",
            "Llueve y el letrero de papel ya no existe. El de verdad se moja en el borde. Lo secas con la manga y abres. Afuera pasa alguien que ya no pregunta qué hay ahí dentro, porque encargó el cartel de su panadería y sabe tu nombre.",
            "No explota ni se cae. Se queda, y es tuyo.",
        ],
    },
    {
        "id": "canal-cae",
        "mode": "creator",
        "ending": "loss",
        "title": "POV: Tu canal llega alto y se apaga",
        "premise": "Tu canal de recetas rápidas llega a cientos de miles de visitas y después se apaga.",
        "name": "Cinco minutos",
        "city": "Sevilla",
        "need": ("canal", "video", "visita", "suscriptor"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "se cae",
        "paras": [
            "Tienes 25 años en Sevilla y el canal se llama Cinco minutos. Subes recetas que entran en la hora del almuerzo: tortilla en una sartén chica, pasta con lo que queda en la heladera. El primer video lo ven 30 personas. Tienes 90 suscriptores. Grabas en la cocina de tus padres, con el micro apoyado en un vaso.",
            "«Tortilla de un huevo» llega a 400.000 visitas un domingo. Los suscriptores pasan a 9.000. Una marca de ollas te paga 1.800 dólares por video. Haces cuatro ese mes: 7.200. Entonces, y no antes, dejas el trabajo de repositor. El apartamento sale 750 al mes. Compras la olla que querías, de 220 dólares, no la del supermercado.",
            "Durante medio año el canal crece. Un video de pasta se queda en 90.000 visitas y te parece poco. Empiezas a repetir el mismo plano porque el de la sartén es el que paga. Tu madre dice que ya no cocinas: encuadras.",
            "Hay una semana floja. El video del jueves no despega: 900 visitas en tres días. El mail de la marca llega el viernes. Cortan los 1.800 dólares. El algoritmo, dicen, y también que ya no se te ve la cara, solo el mango.",
            "Intentas un video largo, de 18 minutos, sin sartén y con tu voz. Lo ven 1.200 personas. Los comentarios preguntan dónde está la receta de un huevo. Tú contestas a tres y después cierras la laptop. Los suscriptores bajan a 6.000. No es una caída de un día. Es un mes en el que cada tarde miras el número y es menor.",
            "Vendes la cámara en 700 dólares para cubrir el alquiler de 750. La cocina de la foto sigue ahí, vacía de ollas. Vuelves a dormir en la casa de tus padres un martes, con la bolsa del micro en el pasillo. Tu padre calienta una tortilla y no la graba. Tú tampoco.",
            "El canal queda en 4.000 suscriptores y el último video, una prueba sin marca, se queda en 200 visitas. Lees los comentarios viejos de los 400.000 y no contestas. La sartén de 220 dólares está en una caja.",
            "Al final se cae. Se cierra esa etapa. Te quedas con el olor de la cocina de tus padres y con un video que ya no subes.",
        ],
    },
    {
        "id": "canal-ajeno",
        "mode": "creator",
        "ending": "ironic",
        "title": "POV: El video que odias es el que explota",
        "premise": "Subes un video en broma y es el que la gente se queda a ver.",
        "name": "Dato sucio",
        "city": "Bogotá",
        "need": ("video", "visita", "suscriptor", "patrocin"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "no es como lo imaginabas",
        "paras": [
            "Tienes 22 años en Bogotá y el canal Dato sucio explica cosas chicas: por qué la tostada cae del lado de la mermelada, cuánto dura un chicle. Tienes 1.800 suscriptores. Un video bueno, para ti, llega a 4.000 visitas y te alcanza para creer.",
            "Una noche, cansado, subes una broma de 40 segundos: rompes un huevo en el micrófono y dices «así suena el lunes». Lo titulas «El lunes, en audio». A la mañana tiene 2.000.000 de visitas. Los suscriptores saltan a 40.000. La gente pide más huevos. Tú querías hablar del chicle.",
            "Una marca de auriculares ofrece 12.000 dólares si el huevo vuelve en cuatro videos: unos 3.000 por video, lo que paga un clip que puede no repetir el millón. Firmas porque el alquiler es de 500. Grabas el segundo huevo con una cámara de 600 dólares, la que puedes pagar sin vaciar el año.",
            "El video serio, «Cuánto dura un chicle de verdad», se queda en 8.000 visitas. El del huevo número tres pasa 900.000. Lees un comentario que dice que sin el huevo no eres nadie. Apagas el teléfono y el aro de luz sigue encendido, caliente, sobre el escritorio que todavía es una tabla.",
            "Con esos 12.000 pagas el depósito de un apartamento un poco más alto y el sillón gris de 980 dólares, y lo pones detrás de cámara para que no salga en el plano del huevo. El alquiler de 500 sigue siendo el número que miras el día 1. Te sacas una foto en ese sillón y no la publicas. La dejas en el carrete, entre 40 tomas del mismo huevo.",
            "Hay una semana en la que intentas no subirlo. El canal no despega ese martes: 3.000 visitas entre todo. Vuelve el huevo el viernes y el número respira. Tú no. Tu hermana te dice, en la cocina, que ya no le cuentas las cosas: se las tiras al micrófono.",
            "El patrocinio de 12.000 dólares se cobra. Compras un micrófono que no necesita un huevo para sonar. El escritorio de verdad espera: no entra en lo que sobra. Igual el video que la gente guarda es el primero, el de la broma, el que hiciste sin querer.",
            "Consigues lo que querías, y no es como lo imaginabas. El canal es grande. La voz que te queda es la del lunes.",
        ],
    },
    {
        "id": "podcast-mesa",
        "mode": "creator",
        "ending": "plateau",
        "title": "POV: Tu podcast se queda en la mesa de la cocina",
        "premise": "Grabas un podcast de madrugada y se queda chico, y es tuyo.",
        "name": "La mesa de las 23",
        "city": "Montevideo",
        "need": ("podcast", "escucha", "episodio"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "se queda",
        "paras": [
            "Tienes 30 años en Montevideo y a las 23 grabas La mesa de las 23, un podcast de una sola silla. El primer episodio, sobre el colectivo de noche, lo escuchan 40 personas. El micrófono es el del teléfono y la mesa es la de la cocina, con una marca de vaso.",
            "Al episodio 12 una oyente escribe que lo puso mientras lavaba platos. Las escuchas llegan a 6.000. No es un salto. Es una persona más cada noche. Una radio chica te ofrece 400 dólares por llevar el episodio a su hora muerta. Dices que sí una vez, y la mesa se oye rara con su música de fondo.",
            "Hay un mes flojo. El episodio sobre tu padre se queda en 800 escuchas y no despega. Lo dejas igual, sin quitarle la pausa en la que se te corta la voz. Tu padre lo escucha al día siguiente y te manda un audio de 12 segundos: «está bien». Nada más.",
            "A los dos años son 30.000 escuchas por episodio y un patrocinio de una librería: 1.200 dólares por mes si nombras un libro que sí leíste. Lo cumples. No aceptas el de una app de sueño que quería que dijeras que te duermes fácil. No te duermes fácil.",
            "Te ofrecen una red por 18.000 dólares, un año y tres meses de lo que te paga la librería, y un estudio con vidrio. Cenas con el número en la cabeza. Al otro día dices que no. La mesa sigue teniendo la marca del vaso. Te compras unos auriculares de 250 dólares, los que querías, y una lámpara que en la foto se ve como una cocina y no como un set.",
            "Un martes se te cae el archivo. Lo vuelves a grabar y suena peor, más honesto. Lo subes igual. 18.000 escuchas. Menos que el anterior. Te quedas. No miras el gráfico a la hora de la cena.",
            "Sigues viviendo en el mismo departamento. La cocina es el estudio. En la heladera hay una foto impresa del episodio 12, la de los platos, que te mandó esa oyente. No es una cima. Es la mesa.",
            "No explota ni se cae. Se queda, y es tuyo.",
        ],
    },
    {
        "id": "directo-ranked",
        "mode": "creator",
        "ending": "pyrrhic",
        "title": "POV: Tu directo de madrugada se llena y pierdes el domingo",
        "premise": "Haces directos de un juego y la sala se llena a las tres de la mañana.",
        "name": "Turno noche",
        "city": "Ciudad de México",
        "need": ("directo", "espectador", "juego"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "no vuelve",
        "paras": [
            "Tienes 21 años y a la una de la mañana enciendes Turno noche, un directo del mismo juego de ranked. La primera noche hay 8 espectadores. Uno es tu primo. El setup es una silla de comedor y un monitor que hereda tu hermano. Ganas dos partidas y pierdes cuatro. Igual saludas a cada nombre.",
            "En seis meses el directo tiene 6.000 espectadores a las tres de la mañana. Una marca de sillas te manda la que querías, y además 4.000 dólares al mes por dejar el logo en el marco durante las horas de directo. Dejas la facultad los jueves. Tu hermana te guarda el almuerzo del domingo y tú llegas cuando ya está frío.",
            "El chat pide que grites más. Tú gritas una noche y las visitas suben a 9.000. Al día siguiente te duele la garganta y el juego te importa menos que el número de arriba a la izquierda. Pierdes una partida que sí querías ganar y sonríes igual, porque el patrocinio se mira el humor, no el ranked.",
            "Hay una semana floja. Caes a 1.500 espectadores y no despega. La marca escribe un mail corto. Tú alargas el directo hasta las seis para recuperar el promedio. Tu hermana entra al cuarto, ve la luz violeta y cierra la puerta sin saludar.",
            "Te mudas a un apartamento donde puedes gritar. Compras el escritorio ancho, de 700 dólares, no el estrecho de la oferta, y tres monitores. Te sacas una foto del setup y la pones de miniatura. Se ve como la vida que la gente te pide. A las cuatro de la mañana sigues ahí, solo, con 6.000 nombres que no saben cómo te llamas fuera del juego.",
            "El domingo de su cumpleaños, tu hermana cumple 19. Tú estás en una final de ranked con 8.000 espectadores. Le mandas un mensaje: «después». Ella contesta con la foto de la mesa, un lugar vacío, el plato que te guardó. No vuelves a ese domingo.",
            "Ganas el patrocinio, el escritorio y una sala que a las tres no cabe en la pantalla. Pierdes la partida de la vida que ocurría de día. El chat escribe «cracks» y tú lees la foto del plato cuando ya cortaste.",
            "Llegas arriba, y el domingo en esa mesa no vuelve.",
        ],
    },
    {
        "id": "halcones-venta",
        "mode": "sports_team",
        "ending": "exit",
        "title": "POV: Vendes el equipo el día que la grada está llena",
        "premise": "Llevas a los Halcones a una noche grande y los vendes en tus términos.",
        "name": "Halcones de Puerto Norte",
        "city": "Puerto Norte",
        "need": ("equipo", "halcones", "contrato", "valor de mercado"),
        "ban": ("subasta",),
        "close": "lo vendes",
        "paras": [
            "Tienes 33 años y los Halcones de Puerto Norte ya no son el gimnasio vacío. Mateo Ruiz sigue de base. Su contrato, el que renovaste, es de 7.500 dólares al mes, 90.000 al año. Su valor de mercado está en 480.000. Una noche cuentas 2.200 personas, el techo del gimnasio, a 8 dólares: 17.600 en una sola puerta.",
            "Una oferta llega un lunes: 650.000 dólares por el equipo, sobre todo por Mateo y por esas noches, no por un estadio que no es tuyo. Tú pides 48 horas. Caminas el gimnasio de noche, con las luces a medias, y tocas la foto de la primera noche, la de 17 personas, que sigue en el pasillo.",
            "Hay una semana floja antes de decidir. Pierden de visita por 8 puntos y el comprador escribe «el valor de mercado aguanta». Tú no contestas. Mateo te pregunta en el vestuario si el contrato de 90.000 sigue siendo con él o con un logo nuevo. Le dices la verdad: todavía no lo sabes.",
            "Cenas con tus padres. Tu madre dice que ya hiciste lo que querías hacer a los 26, cuando pusiste 18.000 dólares y unas llaves que no abrían. Tu padre mira el partido grabado y no opina. Tú sí: quieres irte cuando la grada está así, no cuando vuelva a sonar a hueco.",
            "Firmas al tercer día. 650.000 dólares. Mateo se queda con sus 7.500 al mes y una cláusula que escribiste tú: no lo mueven de ciudad este año. El comprador acepta porque el valor de mercado de 480.000 le importa más que tu frase.",
            "La última noche entras por la misma puerta. No das un discurso. Le dejas a Mateo las llaves del cuarto de video y la foto de las 17 personas. Él la pone en su locker. La grada canta igual, porque el equipo sigue en la cancha aunque tú ya no firmes el sueldo.",
            "Te mudas a un departamento sin vista al gimnasio. Compras una mesa larga, la que querías, y cuelgas una sola foto: no la de las 2.200 personas, la de las 17. El dinero está en la cuenta. El sábado no tienes que abrir.",
            "Al final lo vendes en tus términos y te vas. Los Halcones juegan igual ese sábado.",
        ],
    },
    {
        "id": "futbol-rivera",
        "mode": "freeform",
        "ending": "victory",
        "title": "POV: Compras un club de fútbol que iba a bajar",
        "premise": "Compras el Atlético Rivera, un club de fútbol chico, y lo sacas del descenso.",
        "name": "Atlético Rivera",
        "city": "Rivera",
        "need": ("fútbol", "club", "contrato", "valor de mercado"),
        "ban": ("playoff", "gimnasio", "básquet", "basquet", "startup", "dueño del equipo"),
        "close": "lo logras",
        "user_proposed": True,
        "paras": [
            "Tienes 34 años y el Atlético Rivera, un club de fútbol, juega en una cancha con la pintura comida. Faltan seis fechas y el club está a tres puntos del descenso. El delantero se llama Iván Soler, tiene 27 años, cobra 4.500 dólares al mes. En el portal su valor de mercado es 400.000: eso es lo que pagaría otro club por llevárselo, no su sueldo. Tú pones 250.000 dólares, lo que sale de vender un departamento que no usabas, y firmas un viernes con olor a pasto mojado.",
            "El primer partido en casa entran 1.100 personas. Iván falla un penal. En el túnel te dice que si los 4.500 del mes llegan tarde, se va en diciembre. Tú pagas el lunes, a las nueve, delante de él. No hay discurso. Hay una transferencia y un café.",
            "Hay una tarde floja: pierden 1 a 3 de visita y el valor de mercado de Iván aparece en un portal en 260.000. Lees el número en el autobús. No se lo muestras. Al entrenamiento llevas pelotas nuevas, 1.200 dólares, porque las viejas ya no rebotan parejo.",
            "Dos meses después mete el gol del empate en el minuto 91. La cancha, 6.400 personas, no se sienta. Su valor de mercado vuelve a 510.000. Un club de la capital ofrece 700.000 dólares por él. Iván te mira en la oficina chica, la que tiene una sola ventana al campo. Dice que quiere terminar el año. El contrato lo deja elegir. Tú no lo empujas.",
            "La fecha del descenso llueve. Entran 8.000 personas y mucha gente se queda de pie junto al alambrado. Ganan 2 a 0. Iván asiste el segundo. Tú estás en la tribuna, no en un palco, porque el club no tiene palco. Te tiembla el vaso de plástico.",
            "Con el descenso salvado, el partido de 8.000 personas a 5 dólares la entrada deja 40.000. Con eso pintas la cancha. El aumento de Iván, a 6.500 dólares al mes, sale de las entradas que siguen, no de tu bolsillo. Te mudas a un alquiler de 700 a seis cuadras, con un sillón que elegiste despacio, no el más barato, y una foto del minuto 91 en el pasillo. Tu padre la mira y dice el nombre del club bien, por primera vez.",
            "El portal actualiza el valor de mercado: 800.000 dólares. Tú no vendes. El sábado siguiente entran 5.000 personas a un partido que no define nada, y eso, la gente cuando no hay miedo, es la parte que no esperabas.",
            "Al final lo logras. El Atlético Rivera sigue en la categoría, e Iván sigue con la 9.",
        ],
    },
    {
        "id": "novela-pasillo",
        "mode": "freeform",
        "ending": "ironic",
        "title": "POV: Tu novela se vende y tu madre lee otro capítulo",
        "premise": "Publicas la novela que escribiste de noche y la gente compra otro libro, el que no era.",
        "name": "La luz del pasillo",
        "city": "Rosario",
        "need": ("novela", "ejemplar", "capítulo"),
        "ban": ("playoff", "gimnasio", "básquet", "startup"),
        "close": "no es como lo imaginabas",
        "user_proposed": True,
        "paras": [
            "Tienes 29 años en Rosario y de noche escribes La luz del pasillo en la mesa de la cocina. Son 80.000 palabras sobre tu hermana y un verano. La imprenta del barrio te cobra 900 dólares por 200 ejemplares. Vendes 40 en la feria, a 12 dólares, y firmas con el mismo boli.",
            "Una editorial te ofrece un anticipo de 12.000 dólares si acortas 40 páginas y cambias el final. Firmas. El libro sale con una tapa que no elegiste, amarilla, y en tres meses vende 8.000 ejemplares. A 15 dólares, tu parte sería cerca de 1,50: unos 12.000, que es justo el anticipo. El resto, si llega, llega al año. La gente te escribe por el final nuevo, el que no era el de la cocina.",
            "Tu madre compra dos. Lee el capítulo 4, el del verano, y te dice que esa parte sí eres tú. El final no lo termina. Te manda una foto de la página 90, doblada. Tú querías que leyera la 210, la de la cocina, la que la editorial te hizo sacar.",
            "Hay una semana floja en la que la segunda novela no despega. Escribes 12 páginas y borras 11. La librería te pide otra firma. Cobras la tarde en ejemplares, no en dinero. Sonríes en 80 fotos y en todas la tapa es la amarilla.",
            "Con el anticipo pagas el depósito y un escritorio de madera clara, de 1.050, no el negro en oferta. No te mudas a un departamento nuevo: 12.000 no alcanzan para un contrato en Rosario y para vivir el año. Pones la foto de la página 90 en un marco. No pones la de la fila de la firma, aunque había 80 personas.",
            "Una lectora te dice, en la fila, que lloró con el final. Tú le agradeces y en el camino a casa piensas en el final de la cocina, el que cabe en un cuaderno que nadie editó. Ese cuaderno sigue en el cajón. Tiene el número 210 escrito a mano.",
            "La novela llega a 8.000 ejemplares. Para un libro de cocina literaria en Rosario, eso es mucho. La historia que era tuya se queda en la página que tu madre sí leyó, y en el cuaderno.",
            "Consigues lo que querías, y no es como lo imaginabas.",
        ],
    },
    {
        "id": "piloto-horas",
        "mode": "freeform",
        "ending": "open",
        "title": "POV: Juntas las horas para el examen de vuelo",
        "premise": "Juntas las horas de vuelo y el examen queda para mañana.",
        "name": "la pista",
        "city": "Córdoba",
        "need": ("vuelo", "hora", "examen"),
        "ban": ("playoff", "gimnasio", "básquet", "startup"),
        "close": "mañana lo miras",
        "user_proposed": True,
        "paras": [
            "Tienes 26 años en Córdoba y el instructor se llama Rosa. La hora de vuelo sale 180 dólares. Llevas 40 horas y el examen de comercial pide 200. Faltan 160 horas: 28.800 dólares. Trabajas en un depósito de lunes a viernes y vuelas cuando esa plata existe. El cuaderno de Rosa tiene tu nombre y una columna que sube de a uno.",
            "Vendes la moto en 3.200 dólares. A 180 la hora son 17 horas, y llegas a 57, no a 150. El depósito te deja pagar una hora por semana.",
            "A las 58 horas te suelta en el circuito. Aterrizas dos veces bien y una dura, que te sacude los dientes. Rosa anota «otra». No es un reto. Es 180 dólares más. Tú asientes y pides la pista otra vez antes de que el miedo se siente.",
            "Hay un mes flojo. Se rompe el avión, un Cessna de 1978, y la hora no se vuela. El taller pasa un presupuesto de 4.000 dólares que no es tuyo, pero el calendario sí. Pierdes tres sábados. El examen se corre. Tú sigues en el depósito, contando cajas, con el cuaderno en la mochila. Rosa te dice que el despegue ya es tuyo y que el aterrizaje con viento cruzado todavía no. Una tarde el viento está en 18 nudos y lo haces. Ella no aplaude. Marca la columna.",
            "A los tres años, sumando sábados, llegas a 190 horas. Un conocido te ofrece fumigar por 2.800 dólares al mes, si apruebas. Tú no contestas ese día. Quieres el examen antes que el sueldo. Tu madre te pregunta si el depósito era tan malo. Le dices que no era malo. Era de tierra.",
            "Llegas a 210 horas un viernes, tres años después de la hora 40. El examen es el lunes, a las 7:10, con un inspector que Rosa respeta y no halaga. La tasa del examen son 600 dólares. Los pagas el viernes, en la misma ventanilla donde pagaste la primera hora. Te tiembla el cambio en la mano.",
            "El domingo no vuelas. En casa dejas el cuaderno abierto en la página de las 210. Cuelgas una foto del Cessna, la que tomaste desde la cabina, en la heladera de tu cuarto. No es un título. Es la pista de mañana.",
            "Queda algo abierto. Mañana lo miras.",
        ],
    },
    {
        "id": "pan-cuatro",
        "mode": "chef",
        "ending": "victory",
        "title": "POV: Abres la panadería a las cuatro de la mañana",
        "premise": "Amas de madrugada y la cola llega a la esquina.",
        "name": "Cuatro en punto",
        "city": "Oaxaca",
        "need": ("pan", "horno", "hogaza"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "lo logras",
        "paras": [
            "Tienes 32 años en Oaxaca y el horno de la esquina se alquila de madrugada. La hora sale 15 dólares. A las cuatro entras solo y amasas el pan de agua que te enseñó tu abuela. La primera mañana vendes 20 hogazas a 1 dólar. El horno, cuatro horas, te costó 60. Cierras con las manos blancas y con 40 dólares menos que al entrar.",
            "Pones un nombre en un cartón: Cuatro en punto. A los dos meses son 80 hogazas y una fila de ocho personas que conocen la hora. El costo de la harina sube y tú no subes el precio esa semana. Ganas menos. La fila se queda. Una vecina te dice que el de ayer estaba más tostado y que así le gusta.",
            "Hay una semana floja. Se te quema una horneada entera, 40 hogazas, y el olor llega a la calle. No despega el sábado: vendes 25 y tiras el resto. Tu abuela pasa, parte una pieza quemada y dice que la sal fue poca, no el fuego. Tú anotas eso en el cuaderno, al lado de las cuentas.",
            "En dos años ahorras 9.000 dólares. Compras un horno usado de 7.500 y pagas el primer mes del local, 900. Te quedan 600. El cartel ya no es de cartón. Es de metal, el que querías, no la lona barata. En la pared pones una foto de tu abuela con harina en el delantal.",
            "La fila llega a la esquina: 180 hogazas un domingo, a 1,50. Entras a las tres y media. Tu hermano reparte y cobra. Tú no sales a saludar hasta que el horno está vacío. Una cafetería te pide 60 piezas al día, a 1,20, y dices que sí solo entre semana, porque el domingo es de la cola de la esquina.",
            "Te mudas arriba del local. El departamento huele a corteza. Compras una mesa de madera, de 400 dólares, no la plástica, y desayunas ahí una sola vez, a las once, cuando ya cerraste. La foto de la abuela se ve desde la escalera.",
            "Un martes llueve y entran igual 100 personas. El pan se acaba a las nueve. Cuelgas el cartel de «mañana a las cuatro» y la gente lo lee sin enojarse, porque ya conoce la hora.",
            "Al final lo logras. El horno es tuyo y la esquina también.",
        ],
    },
    {
        "id": "cafe-segunda",
        "mode": "chef",
        "ending": "plateau",
        "title": "POV: Dices que no a la segunda cafetería",
        "premise": "Tu cafetería funciona y dejas pasar el segundo local.",
        "name": "La segunda no",
        "city": "Valparaíso",
        "need": ("café", "taza", "local"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "se queda",
        "paras": [
            "Tienes 27 años en Valparaíso y el local tiene ocho mesas. El café sale 2 dólares y la masa, 3. La primera semana vendes 40 tazas al día, a 2 dólares: unos 2.000 al mes. El alquiler es de 1.300 y el café y la leche se comen el resto. Tú no te pagas. Duermes poco y el expreso te queda amargo el martes, y alguien te lo dice con cariño.",
            "Al año son 140 tazas y una fila que a las nueve dobla hasta la puerta, sin salir a la calle. Una nota en el diario dice el nombre del local y el de la masa de hojaldre. Subes la masa a 4 dólares. Se quedan 130 tazas. No era el precio. Era la mesa de la ventana, la que mira el puerto.",
            "Te ofrecen un segundo local en el centro, llave en mano, por 80.000 dólares. El número es serio. Lo caminas un domingo, vacío, con olor a pintura. Cabe el doble de mesas. No cabe el puerto. Hay una semana en la que no despega la decisión y contestas tarde los mensajes del corredor.",
            "Dices que no. El corredor insiste con una rebaja a 70.000. Vuelves a decir que no, en una frase, sin explicación larga. Esa noche cenas en la mesa de la ventana después de cerrar, con una masa que salió torcida y que igual te comes.",
            "Con esas 130 tazas y la masa, el mes deja para pagarte y para Leo. Entonces compras la máquina de 6.400 dólares, no la de entrada que silba. Leo prueba el primer expreso y asiente. El sillón verde de 900 espera: el alquiler de tu casa sigue primero. Pones una foto del puerto, tomada desde la mesa uno, en el recibidor.",
            "Un mes flojo caen a 90 tazas. Llueve dos semanas. No despides a Leo. Bajas el pedido de leche y aguantas. Al otro mes vuelven las 140 y la fila de las nueve. No abres sucursal. Abres el mismo local, a la misma hora.",
            "La máquina nueva se ve en la foto que la gente saca del mostrador. Tú sales poco. Sales en el reflejo, con el delantal, y te parece suficiente.",
            "No explota ni se cae. Se queda, y es tuyo.",
        ],
    },
    {
        "id": "gira-vacia",
        "mode": "musician",
        "ending": "loss",
        "title": "POV: Sales de gira y las salas se vacían",
        "premise": "Armas una gira con tu banda y las salas dejan de llenarse.",
        "name": "Los del fondo",
        "city": "Lima",
        "need": ("gira", "sala", "canción"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "se cae",
        "paras": [
            "Tienes 24 años y la banda se llama Los del fondo. El nombre es tuyo. La canción que la gente pide es «Semáforo». En Lima, un bar te paga 300 dólares y entran 80 personas. El baterista, Nico, tiene un contrato de palabra: partes iguales de lo que sobre después de la gasolina. Ensayan en la casa de tu madre, en el cuarto que da a la calle.",
            "Armas seis fechas. La primera, en una ciudad chica, garantiza 800 dólares y entran 200 personas. Vendes 40 discos a 10. En el camerino hay una mesa coja y una foto vuestra clavada con cinta. Nico dice que así se siente una gira. Tú le crees.",
            "La tercera fecha garantiza 800 y entran 30. El promoter te paga 400 y promete el resto. El resto no llega. Duermen en el auto. La canción suena igual de bien y el eco de la sala vacía la hace larga. Hay una noche floja en la que no despega ni el saludo: la gente habla encima del estribillo.",
            "Nico pide su parte de las fechas buenas, 600 dólares, y tiene razón. Tú le pagas con lo de los discos y con 200 que eran del alquiler. La cuarta fecha se cancela. El cartel, impreso en 150 copias, queda en el baúl.",
            "Vuelven a Lima. El bar de siempre ofrece 150 dólares, la mitad. Entran 25 personas, varias de tu familia. «Semáforo» suena y tu madre la canta. Tú miras las sillas vacías y agradeces el micrófono, que es el mismo de la primera noche, de 180 dólares, el que no cambiaste por uno brillante.",
            "Nico se va a otra banda un jueves. Te deja el redoblante y una nota: «cuando la sala vuelva, avísame». No hay pelea. Hay una cuenta que ya no cierra. Tú guardas la foto del camerino. Entran 200 en esa foto. En la sala de hoy no.",
            "La última fecha la tocas solo, con la guitarra, por 80 dólares. Terminas «Semáforo» y no hay bis. El dueño del bar te paga en efectivo, contado, y te desea suerte como se le desea a alguien que ya se va.",
            "Al final se cae. Se cierra esa etapa. Te quedas con la canción y sin la sala.",
        ],
    },
    {
        "id": "fotos-boda",
        "mode": "business",
        "ending": "victory",
        "title": "POV: Cobras la boda y armas el estudio que querías",
        "premise": "Fotografías bodas y un día el estudio deja de ser la mesa de la cocina.",
        "name": "Rollo 36",
        "city": "Montevideo",
        "need": ("foto", "boda", "cámara"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "lo logras",
        "paras": [
            "Tienes 27 años y firmas las fotos con Rollo 36. La primera boda te paga 400 dólares y el novio te presta una silla para cambiar el lente. Tu cámara es usada, de 700 dólares, con una raya en el visor. Editas en la mesa de la cocina hasta las tres.",
            "A la quinta boda cobras 1.200. Una novia llora con la foto del padre en la puerta y te escribe a la semana: «esa». Tú la imprimes en 30 por 40 y no se la cobras. Esa impresión te trae otras dos bodas. El número empieza a ser un oficio y no un favor.",
            "Hay un sábado flojo. Llueve, el salón está oscuro y el novio te dice que las fotos no despegan, que se ven tristes. Tú entregas 200 archivos. Él publica 4. Tú te quedas con una, la del zapato de la novia en el charco, y no la muestras. Duele más que un mail frío.",
            "A los dos años la boda sale 2.400 dólares y tienes lista de espera de tres meses. Compras la cámara que querías, de 3.100, no la oferta del año pasado. El visor no tiene raya. Igual extrañas el peso de la vieja el primer fin de semana y la dejas de repuesto en la bolsa.",
            "Alquilas un estudio chico, 700 dólares al mes, con una pared gris y una ventana al oeste. Te mudas a un apartamento arriba. Compras el sofá verde, de 1.100, el que se ve bien en los retratos y que no era el más barato. Pones una foto impresa, la del zapato en el charco, donde solo la ves tú.",
            "Tu madre viene a hacerse un retrato. No le cobras. Tarda 40 minutos en elegir cuál le gusta y se queda con la que sale riéndose a medias. La cuelga en su comedor. Tú la ves cada domingo y entiendes para qué era la cámara.",
            "Un cliente te pide que abarates a 900 y hagas dos bodas el mismo día. Dices que no. El sábado tienes una sola, a 2.400, y llegas a tiempo al brindis. La luz del oeste entra como en la prueba de la pared gris.",
            "Al final lo logras. El estudio es tuyo y la foto también.",
        ],
    },
    {
        "id": "ropa-drop",
        "mode": "business",
        "ending": "pyrrhic",
        "title": "POV: Tu ropa se agota y no llegas a la prueba",
        "premise": "Sacas una tanda de ropa que se vende en un día, y llegas tarde a la prueba de tu hermana.",
        "name": "Tela viva",
        "city": "Medellín",
        "need": ("prenda", "tela", "hermana"),
        "ban": ("playoff", "gimnasio", "básquet", "dueño del equipo"),
        "close": "no vuelve",
        "paras": [
            "Tienes 26 años en Medellín y coses de noche con el nombre Tela viva. La primera tanda son 30 prendas, todas camisas, a 40 dólares. Vendes 12. Tu hermana, Lara, es la que se prueba los prototipos y te dice si la sisa aprieta. La mesa del comedor es el taller. Hay hilos en el arroz.",
            "Un sábado subes 200 camisas a 40 dólares. A las seis no queda ni una. Entran 8.000 dólares, no una fortuna: 200 por 40. La página se traba una vez. Tú miras el número de rodillas, en el suelo, entre cajas. Lara te llama para la prueba de su obra, a las ocho. Le dices que vas.",
            "No vas. A las ocho sigues contestando mails de tallas. Ella te manda una foto del escenario vacío, antes de salir, con la silla que te guardó en primera fila. La silla se ve en la foto. Tú no. Hay una semana floja después, de devoluciones: 30 camisas, 1.200 dólares que salen de los 8.000, y un silencio de Lara que no es un enojo ruidoso.",
            "Con lo que queda alquilas una mesa en un taller compartido, 400 dólares al mes, no un local entero. Compras una máquina usada de 900, no la de 2.200. Te sacas una foto entre los rollos de tela y la pones en la página. Se ve como un oficio. Se siente como una disculpa que todavía no dijiste.",
            "La segunda tanda son 150 camisas a 55 dólares. Se venden en una semana: 8.250. Contratas a una persona, dos días por semana. Lara pasa, se prueba una camisa y dice que la sisa está bien. No habla de la obra. Tú tampoco. La foto del escenario sigue en tu teléfono, sin abrir del todo.",
            "Te mudas a un apartamento sin mesa de corte. Compras un sofá de lino, de 1.300 dólares, el que Lara había señalado en una vidriera meses antes. Lo dejas vacío la primera noche. Le escribes: «está el sofá». Ella contesta al día siguiente: «qué bueno». Nada más.",
            "La marca crece y la sisa queda perfecta. La silla de primera fila, esa noche, no vuelve a estar guardada para ti.",
            "Llegas arriba, y esa prueba no vuelve.",
        ],
    },
]
